// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyzyazhdilxowddumgnt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5enlhemhkaWx4b3dkZHVtZ250Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NjE4MTIsImV4cCI6MjA2NzEzNzgxMn0.oXr31UheQOXWOCHJTcDqFWPG0eWm5tvXV08XD6mr1zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});